### ISSUE TITLE
Need of createAndroidComposeRule to capture non compose screen

### ISSUE THREAD

**Issue by nlokesh-github** [takahirom/roborazzi#126]
A project with compose enabled can have Screens written using view-system as well. Why do we need to use `createAndroidComposeRule<Activity>()` to capture screen level image even when the activity's UI is written using view system?

In a compose enabled project, calling 

```
@Test
  @Config(qualifiers = "+land")
  fun captureRoboImageSample() {
    // launch
    ActivityScenario.launch(MainActivity::class.java)
    // screen level image
    onView(ViewMatchers.isRoot())
      .captureRoboImage()
  }
```

ends up with following crash

```
java.lang.NullPointerException
	at com.github.takahirom.roborazzi.RoboCanvas.save(RoboCanvas.kt:195)
	at com.github.takahirom.roborazzi.RoborazziKt.processOutputImageAndReport(Roborazzi.kt:653)
	at com.github.takahirom.roborazzi.RoborazziKt.access$processOutputImageAndReport(Roborazzi.kt:1)
	at com.github.takahirom.roborazzi.RoborazziKt$captureRoboImage$1.invoke(Roborazzi.kt:99)
	at com.github.takahirom.roborazzi.RoborazziKt$captureRoboImage$1.invoke(Roborazzi.kt:98)
	at com.github.takahirom.roborazzi.RoborazziKt.capture(Roborazzi.kt:707)
	at com.github.takahirom.roborazzi.ImageCaptureViewAction.perform(Roborazzi.kt:681)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:25)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:7)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:938)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:99)
	at android.os.Handler.dispatchMessage(Handler.java)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:368)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:402)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:93)
	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:18)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:98)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:87)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage$default(Roborazzi.kt:82)
```

**Comment by sergio-sastre** [comment]
> A project with compose enabled can have Screens written using view-system as well. Why do we need to use `createAndroidComposeRule<Activity>()` to capture screen level image even when the activity's UI is written using view system?
> 
> In a compose enabled project, calling
> 
> ```
> @Test
>   @Config(qualifiers = "+land")
>   fun captureRoboImageSample() {
>     // launch
>     ActivityScenario.launch(MainActivity::class.java)
>     // screen level image
>     onView(ViewMatchers.isRoot())
>       .captureRoboImage()
>   }
> ```
> 
> ends up with following crash
> 
> ```
> java.lang.NullPointerException
> 	at com.github.takahirom.roborazzi.RoboCanvas.save(RoboCanvas.kt:195)
> 	at com.github.takahirom.roborazzi.RoborazziKt.processOutputImageAndReport(Roborazzi.kt:653)
> 	at com.github.takahirom.roborazzi.RoborazziKt.access$processOutputImageAndReport(Roborazzi.kt:1)
> 	at com.github.takahirom.roborazzi.RoborazziKt$captureRoboImage$1.invoke(Roborazzi.kt:99)
> 	at com.github.takahirom.roborazzi.RoborazziKt$captureRoboImage$1.invoke(Roborazzi.kt:98)
> 	at com.github.takahirom.roborazzi.RoborazziKt.capture(Roborazzi.kt:707)
> 	at com.github.takahirom.roborazzi.ImageCaptureViewAction.perform(Roborazzi.kt:681)
> 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
> 	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:25)
> 	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(ViewInteraction.java)
> 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:7)
> 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:938)
> 	at android.os.Handler.handleCallback(Handler.java)
> 	at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:99)
> 	at android.os.Handler.dispatchMessage(Handler.java)
> 	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:368)
> 	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:402)
> 	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:93)
> 	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:18)
> 	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:1)
> 	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
> 	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
> 	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:98)
> 	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:87)
> 	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage$default(Roborazzi.kt:82)
> ```

@nlokesh-github 
If you need an Activity scenario in your Robolectric screenshot tests, I strongly recommend to take a look at this library:
https://github.com/sergio-sastre/AndroidUiTestingUtils#robolectric-screenshot-tests-beta

**Comment by nlokesh-github** [comment]
Thanks @sergio-sastre , will explore.

Meanwhile I did use below test with :app module where compose is enabled, and its able to capture the image. Wondering  why does the above crash appears in my project
```
@Test
  @Config(qualifiers = "+land")
  fun captureRoboImageSample() {
    // launch
    ActivityScenario.launch(MainActivity::class.java)
    // screen level image
    onView(ViewMatchers.isRoot())
      .captureRoboImage()
  }
```

**Comment by takahirom** [comment]
@nlokesh-github 

Thank you for reporting this issue.

```
java.lang.NullPointerException
at com.github.takahirom.roborazzi.RoboCanvas.save(RoboCanvas.kt:195)
at com.github.takahirom.roborazzi.RoborazziKt.processOutputImageAndReport(Roborazzi.kt:653)
```

I'm not certain why this is happening.

The error could be originating from here. However, I'm not certain why parentFile is null. Could you possibly debug this code by adding a dependency on roborazzi-painter to the debug? Alternatively, could you provide a project that can reproduce the error?

```
fun save(file: File, resizeScale: Double) {
drawPendingDraw()
val directory = file.parentFile
if (!directory.exists()) { // ←
directory.mkdirs()
}
```

**Comment by nlokesh-github** [comment]
Issue seems to be local to host machine, not reproducible again with same env, Will close the issue, thanks for the response.
