### ISSUE TITLE
Improve error when a golden image doesn't exist

### ISSUE THREAD

**Issue by JoseAlcerreca** [takahirom/roborazzi#131]
Currently, if you `verify` when the golden is not present:

```
java.lang.AssertionError: Roborazzi: [removed]/ForYouScreenLoading_foldable_compare.png is added.
See compare image at [removed]/ForYouScreenLoading_foldable_compare.png
	at com.github.takahirom.roborazzi.RoborazziOptions$RoborazziCompareReporter$VerifyRoborazziCompareReporter.report(capture.kt:349)
	at com.github.takahirom.roborazzi.RoborazziKt.processOutputImageAndReport(Roborazzi.kt:650)
	at com.github.takahirom.roborazzi.RoborazziKt.access$processOutputImageAndReport(Roborazzi.kt:1)
	at com.github.takahirom.roborazzi.RoborazziKt$captureRoboImage$2.invoke(Roborazzi.kt:274)
	at com.github.takahirom.roborazzi.RoborazziKt$captureRoboImage$2.invoke(Roborazzi.kt:267)
	at com.github.takahirom.roborazzi.RoborazziKt.capture(Roborazzi.kt:708)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:267)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:259)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage$default(Roborazzi.kt:254)
```

The "Error" is not "the png is added". It should say that the original file doesn't exist or that there are differences between the images.

**Comment by takahirom** [comment]
Thank you for the feedback. I'm planning to make the following changes. Do you see any other areas that could be improved?

```diff
-            "Roborazzi: ${compareReportCaptureResult.compareFile.absolutePath} is added.\n" +
-              "See compare image at ${compareReportCaptureResult.compareFile.absolutePath}"
+            "Roborazzi: The original file (${compareReportCaptureResult.goldenFile.absolutePath}) was not found.\n" +
+              "See the actual image at ${compareReportCaptureResult.actualFile.absolutePath}"
```

https://github.com/takahirom/roborazzi/pull/133/files#diff-56dd94f09cbeedc48d8c6e7b9c7d0c9453f25103df63997b6c76da895919f352L96-R97
