### ISSUE TITLE
java.lang.IllegalArgumentException: Window doesn't have a backing surface!

### ISSUE THREAD

**Issue by timothyfroehlich** [takahirom/roborazzi#164]
I'm working on adding Roborazzi to my repo and have gotten blocked on this error. 

We have an android library that extends Jetpack Compose so I'm trying to add some basic tests that will be expanded upon. I've added Roborazzi to one of our reference apps and that's working great, no problems. But I'm getting the above error when I try to add Roborazzi to tests in the main Android library.  I haven't been able to figure out what's wrong or how to get it to work.

I've uploaded a reproduction branch here: https://github.com/google/automotive-design-compose/tree/wb/froeht/robo-failure-repro

The working test is in `reference-apps/helloworld/src/testDebug/kotlin/RenderHelloWorld.kt` and can be run with `./gradlew hello:recordRoborazziDebug`

The failing test is in `designcompose/src/testDebug/kotlin/com/android/designcompose/TestDesignSwitcher.kt` and can be run with `./gradlew designCompose:recordRoborazziDebug`

The full stack trace is below:

```
java.lang.IllegalArgumentException: Window doesn't have a backing surface!
	at android.view.PixelCopy.request(PixelCopy.java:270)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmapFromPixelCopy(ViewScreenshot.kt:181)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmapFromPixelCopy(ViewScreenshot.kt:164)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmap(ViewScreenshot.kt:103)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.fetchImage(ViewScreenshot.kt:28)
	at com.github.takahirom.roborazzi.ComposeScreenshotKt.fetchImage(ComposeScreenshot.kt:30)
	at com.github.takahirom.roborazzi.RoboComponent$Compose.<init>(capture.kt:110)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:219)
	at com.github.takahirom.roborazzi.RoborazziRule.runTest(RoborazziRule.kt:228)
	at com.github.takahirom.roborazzi.RoborazziRule.access$runTest(RoborazziRule.kt:27)
	at com.github.takahirom.roborazzi.RoborazziRule$apply$1.evaluate(RoborazziRule.kt:132)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:272)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:271)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:512)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:330)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTextInputService(ComposeUiTest.android.kt:396)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTextInputService(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:329)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:383)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:328)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:357)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:327)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:370)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:326)
	at androidx.compose.ui.test.junit4.IdlingStrategy.withStrategy(IdlingStrategy.android.kt:52)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:325)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:157)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:324)
	at androidx.compose.ui.test.junit4.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:323)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:271)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	```

**Comment by takahirom** [comment]
Thank you for trying it out!
I believe you can resolve the issue by specifying the SDK version as follows:

@Config(
    sdk = [33],
    qualifiers = RobolectricDeviceQualifiers.MediumTablet,
)

We've issued a warning regarding this. It appears that your SDK_INT is set to 26, and we recommend using 28 or higher to avoid the error you mentioned. I'll update it to 28. Thanks for the report!

    if (Build.VERSION.SDK_INT < 26) {
      println(
        "**Warning from Roborazzi**: Robolectric may not function properly on API 26 or lower, " +
          "specifically, it may fail to capture accurate screenshots. " +
          "Please add @Config(sdk = [26]) or higher to your test class to ensure proper functionality. " +
          "For more details, please refer to https://github.com/takahirom/roborazzi/issues/114 ."
      )
    }

**Comment by takahirom** [comment]
@timothyfroehlich 
If the issue persists or if there are any other problems, please let me know and I'll reopen this issue.

**Comment by timothyfroehlich** [comment]
That seems to have done it, though if I set the API to 31, 32 or 33 I get these warnings:

```
com.android.designcompose.TestDesignSwitcher > testExpand STANDARD_ERROR
    System.logW: No Compatibility callbacks set! Querying change 210923482
    System.logW: No Compatibility callbacks set! Querying change 171228096
    System.logW: No Compatibility callbacks set! Querying change 171228096
    System.logW: No Compatibility callbacks set! Querying change 171228096
    System.logW: No Compatibility callbacks set! Querying change 171228096
    System.logW: No Compatibility callbacks set! Querying change 171228096
    System.logW: No Compatibility callbacks set! Querying change 171228096
    System.logW: No Compatibility callbacks set! Querying change 171228096
    System.logW: No Compatibility callbacks set! Querying change 171228096

com.android.designcompose.TestDesignSwitcher > testExpand PASSED
```

The warnings go away with API 30, so I'll just stick with that. Thank you for the quick response!
