### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com/github/takahirom/roborazzi/CaptureResult

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#378]
I'm seeing this error 

```
Caused by: java.lang.NoClassDefFoundError: com/github/takahirom/roborazzi/CaptureResult
	at io.github.takahirom.roborazzi.RoborazziPlugin$apply$configureRoborazziTasks$finalizeTestRoborazziTask$1$execute$2.invoke(RoborazziPlugin.kt:237)
	at io.github.takahirom.roborazzi.RoborazziPlugin$apply$configureRoborazziTasks$finalizeTestRoborazziTask$1$execute$2.invoke(RoborazziPlugin.kt:226)
	at io.github.takahirom.roborazzi.RoborazziPlugin$apply$configureRoborazziTasks$finalizeTestRoborazziTask$1.execute$lambda$1(RoborazziPlugin.kt:226)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:835)
```

**Comment by takahirom** [comment]
It is in roborazzi-core/commonJvmMain
https://github.com/takahirom/roborazzi/blob/d90d1c261f5867d269e50bf24b049ac11ddf9892/include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/CaptureResult.kt#L21

**Comment by takahirom** [comment]
We are using api for core module 👀 
https://github.com/takahirom/roborazzi/blob/main/roborazzi/build.gradle#L18

**Comment by takahirom** [comment]
https://repo1.maven.org/maven2/io/github/takahirom/roborazzi/roborazzi-gradle-plugin/1.17.0/

https://repo1.maven.org/maven2/io/github/takahirom/roborazzi/roborazzi-gradle-plugin/1.17.0/roborazzi-gradle-plugin-1.17.0.pom

```
<dependency>
<groupId>io.github.takahirom.roborazzi</groupId>
<artifactId>roborazzi-core-jvm</artifactId>
<version>1.17.0</version>
<scope>runtime</scope>
<exclusions>
<exclusion>
<groupId>junit</groupId>
<artifactId>junit</artifactId>
</exclusion>
</exclusions>
</dependency>
```

https://repo1.maven.org/maven2/io/github/takahirom/roborazzi/roborazzi-core-jvm/

<img width="345" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/298a936b-1632-4a91-a289-e5aaf9de3520">

**Comment by takahirom** [comment]
I was able to solve this issue by adding the Roborazzi plugin to the root module with apply false to include it in the classpath of my project.
