### ISSUE TITLE
Error `Iteration already started` when performing click and using Roborazzi Rule

### ISSUE THREAD

**Issue by bohregard** [takahirom/roborazzi#39]
I have a fairly simple test that presses some buttons to toggle between weeks and update some text to reflect the new week.
When I add Roborazzi, the test fails with the error message `Iteration already started`. I've also noticed that the test times are a lot longer than without Roborazzi (see attached images).

```
@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
class CalendarUiTests {
    @get:Rule
    val composeTestRule = createAndroidComposeRule<ComponentActivity>()

    @get:Rule
    val roborazziRule = RoborazziRule(
        composeRule = composeTestRule,
        captureRoot = composeTestRule.onRoot(),
        options = RoborazziRule.Options(
            captureType = RoborazziRule.CaptureType.LastImage,
        )
    )

    @Before
    @Throws(Exception::class)
    fun setup() {
        ShadowLog.stream = System.out
    }

    @Test
    fun `calendar top bar changes dates`() {
        var start by mutableStateOf(LocalDateTime.of(
            LocalDate.of(2023, 10, 1),
            LocalTime.MIDNIGHT
        ))
        var end by mutableStateOf(LocalDateTime.of(
            LocalDate.of(2023, 10, 7),
            LocalTime.MAX
        ))

        composeTestRule.setContent {
            CalendarTopBar(
                start = start,
                end = end,
                onPreviousWeek = {
                    start = start.minus(7, ChronoUnit.DAYS)
                    end = end.minus(7, ChronoUnit.DAYS)
                },
                onNextWeek = {
                    start = start.plus(7, ChronoUnit.DAYS)
                    end = end.plus(7, ChronoUnit.DAYS)
                }
            )
        }

        composeTestRule.onRoot().printToLog("TAG")

        composeTestRule.onNodeWithTag("calendarTitleBar")
            .assertIsDisplayed()
            .assertTextContains("Oct 1 - Oct 7")

        composeTestRule.onNodeWithTag("buttonPreviousWeek")
            .performClick()

        composeTestRule.onRoot().printToLog("TAG")

        composeTestRule.onNodeWithTag("calendarTitleBar")
            .assertIsDisplayed()
            .assertTextContains("Sep 24 - Sep 30")

        composeTestRule.onNodeWithTag("buttonNextWeek")
            .performClick()
            .performClick() // Fails on this line

        composeTestRule.onNodeWithTag("calendarTitleBar")
            .assertIsDisplayed()
            .assertTextContains("Oct 8 - Oct 14")
    }

}
```
 
If I remove Roborazzi, the test passes with no issues.

CalendarTopBar for reference:

```
@Composable
fun CalendarTopBar(
    start: LocalDateTime,
    end: LocalDateTime,
    onPreviousWeek: () -> Unit,
    onNextWeek: () -> Unit
) {
    val dtf = DateTimeFormatter.ofPattern("MMM d")
    Row(
        modifier = Modifier.padding(10.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Button(
            modifier = Modifier.testTag("buttonPreviousWeek"),
            onClick = {
                onPreviousWeek()
            },
            shape = RoundedCornerShape(2.dp)
        ) {
            Image(
                colorFilter = ColorFilter.tint(MaterialTheme.colorScheme.onPrimary),
                contentDescription = null,
                painter = painterResource(id = R.drawable.ic_arrow_back),
            )
        }
        Spacer(modifier = Modifier.weight(1f))
        Text(
            modifier = Modifier.testTag("calendarTitleBar"),
            style = MaterialTheme.typography.titleLarge,
            text = "${start.format(dtf)} - ${end.format(dtf)}"
        )
        Spacer(modifier = Modifier.weight(1f))
        Button(
            modifier = Modifier.testTag("buttonNextWeek"),
            onClick = {
                onNextWeek()
            },
            shape = RoundedCornerShape(2.dp)
        ) {
            Image(
                colorFilter = ColorFilter.tint(MaterialTheme.colorScheme.onPrimary),
                contentDescription = null,
                painter = painterResource(id = R.drawable.ic_arrow_forward),
            )
        }
    }
}
```

Test times without Roborazzi:
![image](https://user-images.githubusercontent.com/1455137/233487599-8816af51-cc7f-42cb-9130-8c8daaed03d0.png)

Test times with Roborazzi:
![image](https://user-images.githubusercontent.com/1455137/233487672-85ac34ba-6f11-4709-b9ef-b607ff42db4e.png)

**Comment by takahirom** [comment]
I haven't encountered this problem before. Thanks for bringing it up. I'll look into it and see what I can do.
As for the time issue, Roborazzi's rules capture a screenshot for every layout change, which can be time-consuming. However, I'd like to work on improving it. 
In the meantime, could you try using captureRoboImage() as a workaround?

**Comment by bohregard** [comment]
Using `captureRoboImage()` worked and it was surprisingly faster too~

![image](https://user-images.githubusercontent.com/1455137/233520706-4451ceae-9e11-4df9-a882-c21fb070cad6.png)


Thanks for the hard work. 💪 
If you need any thing more from me, let me know.

**Comment by takahirom** [comment]
Thanks for checking.
I would like to know if the stack trace is coming from the Roborazzi side or from the peformClick test side when an error occurs. If it is coming from Roborazzi, it can be determined by whether it is currently running, but if it is coming from performClick, a different implementation may be needed.

**Comment by bohregard** [comment]
Here is the full stack trace:

```
Iteration already started
java.lang.IllegalStateException: Iteration already started
	at android.view.ViewTreeObserver$CopyOnWriteArray.start(ViewTreeObserver.java:1292)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1057)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3352)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:368)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:402)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:93)
	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:18)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:11)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:1)
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.waitForIdle(ComposeUiTest.android.kt:344)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$waitForIdle(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidTestOwner.getRoots(ComposeUiTest.android.kt:561)
	at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:94)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:62)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:128)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
	at com.github.takahirom.roborazzi.RoborazziKt$captureComposeNode$capture$1.invoke(Roborazzi.kt:322)
	at com.github.takahirom.roborazzi.RoborazziKt$captureComposeNode$capture$1.invoke(Roborazzi.kt:319)
	at com.github.takahirom.roborazzi.RoborazziKt.captureComposeNode$lambda$8(Roborazzi.kt:330)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3352)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:368)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:402)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:93)
	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:18)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:11)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:1)
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.waitForIdle(ComposeUiTest.android.kt:344)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$waitForIdle(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidTestOwner.getRoots(ComposeUiTest.android.kt:561)
	at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:94)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:62)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:128)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode$default(SemanticsNodeInteraction.kt:78)
	at androidx.compose.ui.test.OutputKt.printToString(Output.kt:45)
	at androidx.compose.ui.test.OutputKt.printToLog(Output.kt:68)
	at androidx.compose.ui.test.OutputKt.printToLog$default(Output.kt:63)
	at com.bohregard.dopplerr.CalendarUiTests.calendar top bar changes dates(CalendarUiTests.kt:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.github.takahirom.roborazzi.RoborazziRule$apply$1$evaluate$evaluate$1.invoke(RoborazziRule.kt:86)
	at com.github.takahirom.roborazzi.RoborazziRule$apply$1$evaluate$evaluate$1.invoke(RoborazziRule.kt:84)
	at com.github.takahirom.roborazzi.RoborazziKt.captureComposeNode(Roborazzi.kt:355)
	at com.github.takahirom.roborazzi.RoborazziRule$apply$1.evaluate(RoborazziRule.kt:107)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:272)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:271)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:512)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:330)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTextInputService(ComposeUiTest.android.kt:396)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTextInputService(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:329)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:383)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:328)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:357)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:327)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:370)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:234)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:326)
	at androidx.compose.ui.test.junit4.IdlingStrategy.withStrategy(IdlingStrategy.android.kt:52)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:325)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:157)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:324)
	at androidx.compose.ui.test.junit4.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:323)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:271)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by takahirom** [comment]
Thanks!

**Comment by takahirom** [comment]
📝 
It occurs when using ViewTreeObserver's listener, so I should probably use a handler.post() in the listener.
