### ISSUE TITLE
Dialog in Compose Preview causes `IllegalStateException` in generated tests

### ISSUE THREAD

**Issue by ashughes** [takahirom/roborazzi#554]
## Repro

Add the following to `Previews.kt` in `sample-generate-preview-tests`:

```kotlin
@Preview
@Composable
fun PreviewDialog() {
  MaterialTheme {
    AlertDialog(
      onDismissRequest = {},
      confirmButton = @Composable { Text("Confirm") },
      text = @Composable { Text("Generate Preview Test Sample!") }
    )
  }
}
```

Run `./gradlew :sample-generate-preview-tests:recordRoborazziDebug` and observe the following output:

```
RoborazziPreviewParameterizedTests > test[com.github.takahirom.preview.tests.PreviewsKt_PreviewDialog] FAILED
    java.lang.IllegalStateException at RoborazziPreviewParameterizedTests.kt:38

6 tests completed, 1 failed

> Task :sample-generate-preview-tests:testDebugUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-generate-preview-tests:testDebugUnitTest'.
```

<details>
<summary>Stacktrace of failed test</summary>

```
java.lang.IllegalStateException: Unable to find the image of the target root component. Does the rendering element exist?
	at com.github.takahirom.roborazzi.RoborazziKt.capture(Roborazzi.kt:618)
	at com.github.takahirom.roborazzi.ImageCaptureViewAction.perform(Roborazzi.kt:592)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:25)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:7)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:942)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:99)
	at android.os.Handler.dispatchMessage(Handler.java)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.doRun(ShadowPausedLooper.java:600)
	at org.robolectric.shadows.ShadowPausedLooper$ControlRunnable.run(ShadowPausedLooper.java:563)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:685)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:104)
	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:18)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:56)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:85)
	at com.github.takahirom.roborazzi.RoborazziComposeKt.captureRoboImage$lambda$1$lambda$0(RoborazziCompose.kt:42)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$androidx-test-core-app-ActivityScenario(ActivityScenario.java:789)
	at androidx.test.core.app.ActivityScenario$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:799)
	at com.github.takahirom.roborazzi.RoborazziComposeKt.captureRoboImage(RoborazziCompose.kt:36)
	at com.github.takahirom.roborazzi.RoborazziComposeKt.captureRoboImage(RoborazziCompose.kt:20)
	at com.github.takahirom.roborazzi.RoborazziPreviewScannerSupportKt.captureRoboImage(RoborazziPreviewScannerSupport.kt:17)
	at com.github.takahirom.roborazzi.RoborazziPreviewScannerSupportKt.captureRoboImage$default(RoborazziPreviewScannerSupport.kt:11)
	at com.github.takahirom.roborazzi.AndroidComposePreviewTester.test(RoborazziPreviewScannerSupport.kt:112)
	at com.github.takahirom.roborazzi.RoborazziPreviewParameterizedTests.test(RoborazziPreviewParameterizedTests.kt:38)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:291)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

The cause of the `IllegalStateException` is that the `View` returned by `ViewFinder.getView()` inside `ViewInteraction.doPerform()` has a 0 width/height and is being passed into `RoboComponent.View` inside `ImageCaptureViewAction.perform()`. This causes `View.fetchImage()` inside `ViewScreenshot.kt` to return `null`, which then throws the `IllegalStateException` since `rootComponent.image` is `null`.

I'm not sure what the cause of the `View` having a 0 width/height is. I'm not able to step through the espresso code as it says "Library source does not match the bytecode for class `ViewInteraction.java`." However, I do see that `view.isAttachedToWindow = true` and `mRootView` is a `DecoreView[RoborazziTransparentActivity]`.

**Comment by takahirom** [comment]
Thanks. It's a little more difficult than I thought. The size of the decor view of the dialog seems to be zero, and I'm not sure why it is zero.  
Sorry, I have a presentation I need to prepare for, but I'll come back on December 1st.  
In the meantime, please add an ignore annotation to the preview or capture the contents of the dialog.


For anyone who wants to fix this issue, I'll leave this code here. If you can figure out why the decor view size is zero, it would be much appreciated.  
You can run the failing test by executing the `com.github.takahirom` package from Android Studio.

<img width="619" alt="image" src="https://github.com/user-attachments/assets/2dccfcab-e773-4c91-b534-c3800f253fab">

https://github.com/takahirom/roborazzi/pull/555/commits/17ef64c8f9e337e724b87c6208ff7467999b96fd

**Comment by ashughes** [comment]
> In the meantime, please add an ignore annotation to the preview or capture the contents of the dialog.

Is there an annotation I can add to our dialog previews that will cause them to get skipped as a temporary workaround? I'm not finding anything in the documentation.

**Comment by takahirom** [comment]
Sorry, but you might need to implement your own `ComposePreviewTester` to add the Ignore annotation.  
For more details, check the following links:  
https://takahirom.github.io/roborazzi/preview-support.html#manually-adding-compose-preview-screenshot-tests  
https://github.com/sergio-sastre/ComposablePreviewScanner  
Alternatively, you can make the Preview function a private function so that it is not scanned by `ComposablePreviewScanner`.

**Comment by savvasenok** [comment]
Having this issue, also while displaying the single `material3.ModalBottomSheetDialog`. Managed to fix it with an empty Scaffold, that - presumably - makes the size non-zero
