### ISSUE TITLE
AssertionError when updating to 1.1.0

### ISSUE THREAD

**Issue by colinrtwhite** [takahirom/roborazzi#77]
Hi, I'm getting the following error when updating from `1.0.0-rc-3` to `1.1.0`:

```
java.lang.AssertionError: Roborazzi: /Users/colinwhite/coil/coil-test-roborazzi/src/test/snapshots/images/coil_test_RoborazziViewTest_loadView_compare.png is added.
See compare image at /Users/colinwhite/coil/coil-test-roborazzi/src/test/snapshots/images/coil_test_RoborazziViewTest_loadView_compare.png
	at com.github.takahirom.roborazzi.RoborazziOptions$RoborazziCompareReporter$VerifyRoborazziCompareReporter.report(capture.kt:270)
	at com.github.takahirom.roborazzi.RoborazziKt.saveOrCompare(Roborazzi.kt:601)
	at com.github.takahirom.roborazzi.RoborazziKt.saveLastImage(Roborazzi.kt:441)
	at com.github.takahirom.roborazzi.RoborazziKt.access$saveLastImage(Roborazzi.kt:1)
	at com.github.takahirom.roborazzi.RoborazziKt$captureAndroidView$3.invoke(Roborazzi.kt:419)
	at com.github.takahirom.roborazzi.RoborazziKt$captureAndroidView$3.invoke(Roborazzi.kt:418)
	at com.github.takahirom.roborazzi.RoborazziRule$apply$1.evaluate(RoborazziRule.kt:125)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

If I generate the `_compare` screenshots with the new `compare` task, the `verify` tasks still fails with the same error. [Here's a PR](https://github.com/coil-kt/coil/pull/1745) that reproduces the issue by running: `./gradlew verifyRoborazziDebug --rerun-tasks`

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I understand that there might be some confusion about how to use Roborazzi tasks correctly. Here's a step-by-step explanation to help clarify the process:

1. First, you need to run the `recordRoborazziDebug` task to save a new image. This is a crucial step to establish a baseline for comparison and to fix the `verify` task when it fails.
```
./gradlew recordRoborazziDebug
```

2. To view changes in the image, run the `compareRoborazziDebug` task. This will save the differences between the current image and the previously saved one as an [original]_compare.png file. It will also generate a JSON file containing the diff information in the build/test-results/roborazzi folder.
```
./gradlew compareRoborazziDebug
```

3. To verify the changes in the image, run the `verifyRoborazziDebug` task. If the image is different from the one previously saved, the test will fail. In this case, you'll need to run the `record` task again to save a new image and resolve the issue.
```
./gradlew verifyRoborazziDebug
```

Please follow these steps to ensure you are using the tasks correctly. If the `verify` task fails, remember to run the `record` task to save a new image and fix the problem. Let me know if you have any further questions or need additional clarification.

**Comment by takahirom** [comment]
I noticed that your RoborazziViewTest uses both RoborazziRule and captureRoboImage(). Just a friendly reminder that RoborazziRule is not necessary when you use captureRoboImage(). Great job so far!

**Comment by colinrtwhite** [comment]
@takahirom Gotcha, thanks. Removing `RoborazziRule` from `RoborazziViewTest` helped. I fixed my issue, though it seems like the default screenshot naming scheme changed in the latest release? `recordRoborazziDebug` creates `coil_test_RoborazziViewTest_loadView.png` instead of `coil.test.RoborazziViewTest_loadView.png` now.

**Comment by takahirom** [comment]
I added a breaking change warning at https://github.com/takahirom/roborazzi/releases/tag/1.0.0-beta-4 . Thanks.

**Comment by takahirom** [comment]
Let me close this issue as I opened https://github.com/takahirom/roborazzi/issues/80 issue 🙏
