### ISSUE TITLE
DefaultFileNameGeneration NoClassDefFoundError crash

### ISSUE THREAD

**Issue by galisamas** [takahirom/roborazzi#95]
In the environment without the Compose and by simply capturing the robo image, `DefaultFineNameGeneration` crashes when trying to search for the test method name.

```
onView(isRoot())
                .captureRoboImage()
```

The stacktrace is:
```
java.lang.NoClassDefFoundError: androidx/compose/ui/test/SemanticsNodeInteraction
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at com.github.takahirom.roborazzi.DefaultFileNameGenerator.generateName(DefaultFileNameGenerator.kt:26)
	at com.github.takahirom.roborazzi.DefaultFileNameGenerator.generateFilePath(DefaultFileNameGenerator.kt:11)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage$default(Roborazzi.kt:67)
```

Not sure why the compose is considered here, but it crashes since the `NoClassDefFoundError` is `Throwable` and not the `Exception`.

`1.1.0` version

**Comment by takahirom** [comment]
Thanks! I'm going to fix this.
